6데이터타입 7.연산_ultraWiseWater.md
=> 6.데이터타입7.연산_ultraWiseWater

12.함수_ultraWiseWater.md
=> 12.함수_ultraWiseWater

18함수와 일급 객체/buyeolim.md
=> 18장 요약파일 추가(#29)

18.함수와 일급 객체_ultraWiseWater.md
=> 18. 함수와 일급 객체_ultraWiseWater

27배열/buyeolim.md
=> 27장 요약파일 추가(#80)

23실행 컨텍스트&13스코프/quiz.md
=> 23_13_quiz 업로드

15.let, const 키워드와 블록 레벨 스코프.md
=> 14. 전역 변수의 문제점, 15.let, const 키워드와 블록 레벨 스코프_ultraWiseWater

25클래스/seongm2n.md
=> 25.클래스_seongm2n

25클래스/LHI0915.md
=> 25.클래스_LHI0915

24클로저/buyeolim.md
=> 24장 요약파일 추가(#77)

19프로토타입/seongm2n.md
=> 19.프로토타입_seongm2n

19프로토타입/buyeolim.md
=> 19장 요약파일 추가(#30)

19.프로토타입.md
=> 19. 프로토타입_ultraWiseWater

20strict mode&21빌트인 객체&22this/buyeolim.md
Issue #31 
- 20장. strict mode
- 21장. 빌트인 객체
- 22장. this
=> 20, 21, 22장 요약파일 추가(#31)

20strict mode&21빌트인 객체&22this/nkavay.md
=> 20.strict mode_21.빌트인 객체_22.this_nkavay

37Set과 Map&42비동기 프로그래밍/buyeolim.md
Issue #101 
- 37장. Set과 Map
- 42장. 비동기 프로그래밍
=> 37, 42장 요약파일 추가(#101)

38브라우저의 렌더링 과정/quiz.md
=> 38_quiz_seongm2n

32String&33Symbol/Quiz.md
Issue #135 
**Quiz.md**
- 32장. String
- 33장. 7번째 데이터 타입 Symbol
퀴즈 파일 추가합니다.
=> 32, 33장 퀴즈파일 추가(#135)

16프로퍼티 어트리뷰트&17생성자 함수에 의한 객체 생성/buyeolim.md
Issue #28
- 16장. 프로퍼티 어트리뷰트
- 17장. 생성자 함수에 의한 객체 생성
=> 16, 17장 요약파일 추가(#28)

26함수의 추가 기능/nkavay.md
=> 26. 함수의 추가 기능_jaeeun

26함수의 추가 기능/buyeolim.md
Issue #79 
- 26장. ES6 함수의 추가 기능
=> 26장 요약파일 추가(#79)

26함수의 추가 기능/quiz_jungmyungjin.md
=> 26.quiz_jungmyungjin

34이터러블&35스프레드 문법&36디스트럭쳐링 할당/buyeolim.md
Issue #100 
- 34장. 이터러블
- 35장. 스프레드 문법
- 36장. 디스트럭처링 할당
=> 34, 35, 36장 요약파일 추가(#100)

32String&33Symbol/seongm2n.md
=> 32.String_33.Symbol_seongm2n

32String&33Symbol/buyeolim.md
Issue #97 
- 32장. String
- 33장. 7번째 데이터 타입 Symbol
=> 32, 33장 요약파일 추가(#97)

32String&33Symbol/LHI0915.md
=> 32.String/33.Symbol_LHI0915

39DOM/buyeolim.md
=> 39장 요약파일 추가(#99)

39DOM/LHI0915.md
=> 39.DOM_LHI0915

39.DOM_ultraWiseWater.md
=> 39. DOM_ultraWiseWater

14,15 quiz.md
=> 14.전역 변수의 문제점 / 15. let, const 키워드와 블록 레벨 스코프

16프로퍼티 어트리뷰트&17생성자 함수에 의한 객체 생성/Quiz.md
=> 16. 프로퍼티 어트리뷰트 / 17. 생성자 함수에 의한 객체 생성 Quiz

25.quiz.md
=> 25.클래스_quiz

40.이벤트/jungmyungjin.md
=> 40.이벤트_jungmyungjin

40.이벤트/buyeolim.md
=> 40장 요약파일 추가(#151)

41.타이머&43.Ajax/buyeolim.md
Issue #152
- 41장. 타이머
- 43장. Ajax
=> 41, 43장 요약파일 추가(#152)

45.프로미스/buyeolim.md
=> 45장 요약파일 추가(#153)

45.프로미스/quiz.md
=> 45프로미스_quiz_seongm2n

46.제너레이터와 async await/buyeolim.md
Issue #154 
- 46장. 제너레이터와 async/await
=> 46장 요약파일 추가(#154)

47.에러처리&48.모듈/buyeolim.md
Issue #156
- 47장. 에러 처리
- 48장. 모듈
=> 47, 48장 요약파일 추가(#156)
